#!/bin/bash

copy_configs() {
    local source_dir="$1"
    local dest_dir="$HOME/.config"

    mkdir -p "$dest_dir"

    for folder in "$source_dir"/*; do
        if [[ -d "$folder" ]]; then
            config_name=$(basename "$folder")
            dest_folder="$dest_dir/$config_name"

            if [[ -d "$dest_folder" ]]; then
                mv "$dest_folder" "$dest_folder.bkp"
            fi

            cp -r "$folder" "$dest_folder"
            echo "Copied $config_name config."
        fi
    done
}

echo "Installing config files..."

echo "Make sure you have installed the following packages:"
echo "- picom for blur effect: https://github.com/ibhagwan/picom-ibhagwan-git"
echo "- i3 for window gaps: https://github.com/Airblader/i3"
echo "Other packages can be installed via your operating system's package manager."

copy_configs "dotfiles"

echo "Note: I've changed keybindings for quitting window to Mod+q in i3. You can modify it in the i3/config file."

echo "Checking dependencies..."

if ! command -v i3 &> /dev/null; then
    echo "i3wm is not installed. Please install it manually using your package manager."
    exit 1
fi

if ! command -v polybar &> /dev/null; then
    echo "Polybar is not installed. Please install it manually using your package manager."
    exit 1
fi

if ! command -v picom &> /dev/null; then
    echo "Picom is not installed. Please install it manually using your package manager."
    exit 1
fi

if ! command -v nitrogen &> /dev/null; then
    echo "Nitrogen is not installed. Please install it manually using your package manager."
    exit 1
fi

echo "Enter your root password to make the polybar and randger modules executable:"
sudo -v

echo "Installing executables in polybar/*.sh and randger/*sh..."
for file in polybar/*.sh randger/*sh; do
    if [[ -x "$file" ]]; then
        sudo cp "$file" "$HOME/.local/bin"
        echo "Copied $file to $HOME/.local/bin."
    fi
done

zenity --title="Installation" --text="Installation complete."